apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  source:
    path: k8s-cluster-configuration/kustomize/platform/core/components/data-management/longhorn/base
  destination:
    namespace: longhorn-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
