apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: false
    pairs:
      argocd.argoproj.io/instance: kubeden-cluster-apps

# Kubernetes Repository
configMapGenerator:
  - name: platform-core-source
    literals:
      - repoURL=https://github.com/kubeden/kubeden.git
    options:
      disableNameSuffixHash: true
      annotations:
        config.kubernetes.io/local-config: "true"

resources:

# Routing
  - routing/traefik/application.yml
  - routing/cert-manager/application.yml
  - routing/external-dns/application.yaml

# Secrets
  - secrets-management/sealed-secrets/application.yml
  - secrets-management/external-secrets/application.yml

# Cloud Integrations
  - cloud-integrations/hcloud-ccm/application.yml
  - cloud-integrations/azure-resource-manager/application.yml
  - cloud-integrations/aws-ack/application.yml
  
# Data Management
  - data-management/longhorn/application.yml
  - data-management/velero/application.yml
  
# Observability
  - observability/prometheus/application.yml
  - observability/grafana/application.yml
  - observability/loki/application.yml
  - observability/tempo/application.yml
  - observability/alloy/application.yml
  
# Resource Management
  - resource-management/metrics-server/application.yml
  - resource-management/reloader/application.yml
  - resource-management/keda/application.yml
  
# Supply Chain
  - supply-chain/zot/application.yml
  - supply-chain/trivy/application.yml

# Policies  
  - policies/kyverno/application.yml


# ---------------------------------------------------------

replacements:
  - source:
      kind: ConfigMap
      name: platform-core-source
      fieldPath: data.repoURL
    targets:
      - select:
          group: argoproj.io
          version: v1alpha1
          kind: Application
        fieldPaths:
          - spec.source.repoURL
        options:
          create: true
