apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
spec:
  project: default
  source:
    targetRevision: main
    path: k8s-cluster-configuration/platform/core/resource-management/keda/base
  destination:
    server: https://kubernetes.default.svc
    namespace: keda
  ignoreDifferences:
    - group: apiregistration.k8s.io
      kind: APIService
      jqPathExpressions:
        - .spec.caBundle
        - .spec.insecureSkipTLSVerify
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[].clientConfig.caBundle
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[].clientConfig.caBundle
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
