apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: azure-service-operator
    repo: https://raw.githubusercontent.com/Azure/azure-service-operator/main/v2/charts
    version: 2.18.0
    releaseName: azure-service-operator
    namespace: azureserviceoperator-system
    valuesFile: values.yml
