apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: argocd
spec:
  project: default
  source:
    path: k8s-cluster-configuration/kustomize/platform/core/components/resource-management/reloader/base
  destination:
    namespace: reloader
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
