apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
spec:
  project: default
  source:
    path: k8s-cluster-configuration/kustomize/platform/core/components/observability/alloy/base
  destination:
    namespace: alloy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
