apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-ack
  namespace: argocd
spec:
  project: default
  source:
    path: k8s-cluster-configuration/kustomize/platform/core/components/cloud-integrations/aws-ack/base
  destination:
    namespace: ack-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
