apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: argocd
spec:
  project: default
  source:
    targetRevision: main
    path: k8s-cluster-configuration/platform/core/resource-management/reloader/base
  destination:
    server: https://kubernetes.default.svc
    namespace: reloader
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
