apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: false
    pairs:
      argocd.argoproj.io/instance: kubeden-apps

resources:
  - company-applications/example-application-01
  - company-applications/example-application-02
  - example-customer-01/example-customer-application-01
  - example-customer-01/example-customer-application-02
