---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-credentials
  namespace: kyverno
spec:
  encryptedData:
    .dockerconfigjson: 
  template:
    metadata:
      creationTimestamp: null
      name: registry-credentials
      namespace: kyverno
    type: kubernetes.io/dockerconfigjson
