apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: platform-core-source
    literals:
      - appOfAppsName=kubeden-cluster-apps
      - repoURL=https://github.com/kubeden/dstack.git
      - targetRevision=main
      - destinationServer=https://kubernetes.default.svc
    options:
      disableNameSuffixHash: true
      annotations:
        config.kubernetes.io/local-config: "true"
