apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: zot
    repo: https://zotregistry.dev/helm-charts
    version: 0.1.106
    releaseName: zot
    namespace: zot
    valuesFile: values.yml

resources:
  - configs/registry-sealed.yaml
