apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k6nis-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kubeden/dstack.git
    targetRevision: main
    path: k8s-cluster-configuration/kustomize/platform/argocd/base/core
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
