replicas: 1

adminUser: admin
adminPassword: kubeden-admin-change-me

persistence:
  enabled: true
  size: 10Gi

serviceMonitor:
  enabled: false

resources:
  requests:
    cpu: 50m
    memory: 128Mi

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        uid: prometheus
        access: proxy
        url: http://prometheus-kube-prometheus-prometheus.prometheus.svc.cluster.local:9090
        isDefault: true
      - name: Loki
        type: loki
        uid: loki
        access: proxy
        url: http://loki-gateway.loki.svc.cluster.local
      - name: Tempo
        type: tempo
        uid: tempo
        access: proxy
        url: http://tempo.tempo.svc.cluster.local:3100
        jsonData:
          tracesToLogsV2:
            datasourceUid: loki
          tracesToMetrics:
            datasourceUid: prometheus
