apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: trivy-operator
    repo: https://aquasecurity.github.io/helm-charts/
    version: 0.32.1
    releaseName: trivy-operator
    namespace: trivy-system
    includeCRDs: true
    valuesFile: values.yml
