apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: ack-chart
    repo: oci://public.ecr.aws/aws-controllers-k8s
    version: 46.86.3
    releaseName: aws-ack
    namespace: ack-system
    includeCRDs: true
    valuesFile: values.yml
